name: Release Build

on:
  # Triggers on version tags in main branch
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - "main"
  
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Only run release steps if we have a version tag on main
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc curl
      
      - name: Install Amber
        run: |
          bash -- <(curl -s "https://raw.githubusercontent.com/amber-lang/amber/master/setup/install.sh") --user
          echo "$HOME/.amber/bin" >> $GITHUB_PATH
      
      - name: Compile Amber scripts
        run: |
          amber installer.ab installer.sh
          amber launcher.ab launcher.sh
      
      - name: Create Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          name: "Release ${{ github.ref_name }}"
          files: |
            installer.sh
            launcher.sh
          fail_on_unmatched_files: true
          generate_release_notes: true
          make_latest: true
      